# Generated by Django 5.1.3 on 2024-11-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_heading', models.CharField(max_length=60, verbose_name='Notice Heading')),
                ('notice_content', models.TextField()),
                ('notice_of_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('notice_poster', models.ImageField(upload_to='notices')),
                ('notice_uploaded_by', models.CharField(default='Media team', max_length=20)),
            ],
        ),
    ]
