# Generated by Django 5.1.3 on 2024-11-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='notice_content',
            new_name='Notice_Content',
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='notice_poster',
            new_name='Notice_Poster',
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='notice_uploaded_by',
            new_name='Notice_Uploaded_By',
        ),
        migrations.RenameField(
            model_name='blogs',
            old_name='notice_of_date',
            new_name='Notice_of_Date',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='notice_heading',
        ),
        migrations.AddField(
            model_name='blogs',
            name='Notice_Heading',
            field=models.CharField(default='Notice One', help_text='Notice Heading', max_length=60),
        ),
    ]
