# Generated by Django 5.1.3 on 2024-11-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='fieldtrips_photos/')),
                ('picture_title', models.CharField(max_length=60)),
                ('caption', models.CharField(default='picture caption', max_length=200)),
                ('place', models.CharField(blank=True, max_length=400, null=True, verbose_name='Place or location of the trip')),
                ('photoDate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
