# Generated by Django 5.1.3 on 2024-11-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=10)),
                ('category', models.CharField(default='', max_length=100)),
                ('subcategory', models.CharField(default='', max_length=100)),
                ('year_issued', models.CharField(default='first year,second year,third year,fourth year,fifth year', max_length=10)),
                ('engineering_group', models.CharField(default='B Eng,B Tech,Diploma,Artisan', max_length=10)),
                ('notes_content', models.FileField(blank=True, null=True, upload_to='notes')),
                ('upload_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
