# Generated by Django 5.1.3 on 2024-11-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssiatantSecretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assiatantSecretary_name', models.CharField(max_length=70)),
                ('status', models.CharField(max_length=15, verbose_name='current or former')),
                ('assiatantSecretary_photo', models.ImageField(default='blank-profile-picture.png', null=True, upload_to='profile_image/')),
                ('assiatantSecretary_attributes', models.CharField(max_length=150, verbose_name='Attributes abouts the club')),
            ],
        ),
        migrations.CreateModel(
            name='AssiatantTresurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assiatantTresurer_name', models.CharField(max_length=70)),
                ('status', models.CharField(max_length=15, verbose_name='current or former')),
                ('assiatantTresurer_photo', models.ImageField(default='blank-profile-picture.png', null=True, upload_to='profile_image/')),
                ('assiatantTresurer_attributes', models.CharField(max_length=150, verbose_name='Attributes abouts the club')),
            ],
        ),
        migrations.CreateModel(
            name='AssistantChairperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistantChairperson_name', models.CharField(max_length=70)),
                ('status', models.CharField(max_length=15, verbose_name='current or former')),
                ('assistantChairperson_photo', models.ImageField(default='blank-profile-picture.png', null=True, upload_to='profile_image/')),
                ('assistantChairperson_attributes', models.CharField(max_length=150, verbose_name='Attributes abouts the club')),
            ],
        ),
        migrations.CreateModel(
            name='Chairperson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chairperson_name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=15, verbose_name='current or former')),
                ('chairperson_photo', models.ImageField(default='blank-profile-picture.png', null=True, upload_to='profile_image/')),
                ('chairperson_attributes', models.CharField(max_length=100, verbose_name='Attributes abouts the club')),
            ],
        ),
        migrations.CreateModel(
            name='Mediateam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mediateam_name', models.CharField(max_length=70)),
                ('status', models.CharField(max_length=15, verbose_name='current or former')),
                ('officialPhoto', models.ImageField(default='blank-profile-picture.png', upload_to='profile_image/')),
                ('photoDate', models.DateTimeField(auto_now=True)),
                ('mediateam_attributes', models.CharField(max_length=150, verbose_name='Attributes abouts the club')),
            ],
        ),
        migrations.CreateModel(
            name='OrganisingSecretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisingSecretary_name', models.CharField(max_length=70)),
                ('status', models.CharField(max_length=15, verbose_name='current or former')),
                ('organisingSecretary_photo', models.ImageField(default='blank-profile-picture.png', null=True, upload_to='profile_image/')),
                ('organisingSecretary_attributes', models.CharField(max_length=150, verbose_name='Attributes abouts the club')),
            ],
        ),
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrons_name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=15, verbose_name='current or former')),
                ('patrons_photo', models.ImageField(default='blank-profile-picture.png', upload_to='profile_image/')),
                ('patrons_attributes', models.CharField(max_length=100, verbose_name='Attributes abouts the club')),
            ],
        ),
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secretary_name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=15, verbose_name='current or former')),
                ('secretary_photo', models.ImageField(default='blank-profile-picture.png', upload_to='profile_image/')),
                ('secretary_attributes', models.CharField(max_length=150, verbose_name='Attributes abouts the club')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Testimonial_Name', models.CharField(help_text='Name of Testimonial ', max_length=70)),
                ('Testimonial_Position', models.CharField(help_text='Role in the club', max_length=30)),
                ('Testimonial_Photo', models.ImageField(default='blank-profile-picture.png', help_text='Picure of Testimonial person', null=True, upload_to='profile_image/')),
                ('Testimonial_Attributes', models.CharField(help_text='Positive attributes only of maximum length of 25 words', max_length=25)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.CreateModel(
            name='Tresurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tresurer_name', models.CharField(max_length=70)),
                ('status', models.CharField(max_length=15, verbose_name='current or former')),
                ('officialPhoto', models.ImageField(default='blank-profile-picture.png', upload_to='profile_image/')),
                ('tresurer_attributes', models.CharField(max_length=150, verbose_name='Attributes abouts the club')),
                ('photoDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
