# Generated by Django 5.1.3 on 2024-11-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadersapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patron',
            old_name='patrons_name',
            new_name='Patrons_Name',
        ),
        migrations.RenameField(
            model_name='patron',
            old_name='patrons_photo',
            new_name='Patrons_Photo',
        ),
        migrations.RenameField(
            model_name='patron',
            old_name='status',
            new_name='Status',
        ),
        migrations.RemoveField(
            model_name='patron',
            name='patrons_attributes',
        ),
        migrations.AlterField(
            model_name='assiatantsecretary',
            name='assiatantSecretary_attributes',
            field=models.CharField(help_text='Attributes abouts the club', max_length=15),
        ),
        migrations.AlterField(
            model_name='assiatanttresurer',
            name='assiatantTresurer_attributes',
            field=models.CharField(help_text='Attributes abouts the club', max_length=15),
        ),
        migrations.AlterField(
            model_name='assistantchairperson',
            name='assistantChairperson_attributes',
            field=models.CharField(help_text='Attributes abouts the club', max_length=15),
        ),
        migrations.AlterField(
            model_name='chairperson',
            name='chairperson_attributes',
            field=models.CharField(help_text='Attributes abouts the club', max_length=15),
        ),
        migrations.AlterField(
            model_name='mediateam',
            name='mediateam_attributes',
            field=models.CharField(help_text='Attributes abouts the club', max_length=15),
        ),
        migrations.AlterField(
            model_name='organisingsecretary',
            name='organisingSecretary_attributes',
            field=models.CharField(help_text='Attributes abouts the club', max_length=15),
        ),
        migrations.AlterField(
            model_name='secretary',
            name='secretary_attributes',
            field=models.CharField(help_text='Attributes abouts the club', max_length=15),
        ),
        migrations.AlterField(
            model_name='tresurer',
            name='tresurer_attributes',
            field=models.CharField(help_text='Attributes abouts the club', max_length=15),
        ),
        migrations.AddField(
            model_name='patron',
            name='Patrons_Attributes',
            field=models.CharField(default='Patrons attributes', help_text='Attributes abouts the club', max_length=15),
        ),
    ]
